/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Product {
  'id' : bigint,
  'productUrl' : string,
  'name' : string,
  'color' : string,
  'minAge' : bigint,
  'platform' : string,
  'sizes' : Array<string>,
  'imageUrl' : string,
  'occasion' : string,
  'gender' : string,
  'category' : string,
  'maxAge' : bigint,
  'price' : number,
}
export interface ProductFilter {
  'color' : [] | [string],
  'maxPrice' : [] | [number],
  'occasion' : [] | [string],
  'gender' : [] | [string],
  'category' : [] | [string],
  'minPrice' : [] | [number],
}
export interface UserProfile {
  'displayName' : string,
  'stylePreferences' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WishlistItem {
  'productUrl' : string,
  'name' : string,
  'productId' : bigint,
  'platform' : string,
  'imageUrl' : string,
  'forMember' : string,
  'category' : string,
  'price' : number,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], bigint>,
  'addWishlistItem' : ActorMethod<[WishlistItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProductById' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[ProductFilter], Array<Product>>,
  'getUserProducts' : ActorMethod<[Principal], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[Principal], Array<WishlistItem>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeWishlistItem' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];