/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Nat,
  'productUrl' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'minAge' : IDL.Nat,
  'platform' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Text,
  'occasion' : IDL.Text,
  'gender' : IDL.Text,
  'category' : IDL.Text,
  'maxAge' : IDL.Nat,
  'price' : IDL.Float64,
});
export const WishlistItem = IDL.Record({
  'productUrl' : IDL.Text,
  'name' : IDL.Text,
  'productId' : IDL.Nat,
  'platform' : IDL.Text,
  'imageUrl' : IDL.Text,
  'forMember' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'stylePreferences' : IDL.Vec(IDL.Text),
});
export const ProductFilter = IDL.Record({
  'color' : IDL.Opt(IDL.Text),
  'maxPrice' : IDL.Opt(IDL.Float64),
  'occasion' : IDL.Opt(IDL.Text),
  'gender' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
  'minPrice' : IDL.Opt(IDL.Float64),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [IDL.Nat], []),
  'addWishlistItem' : IDL.Func([WishlistItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
  'getUserProducts' : IDL.Func([IDL.Principal], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWishlist' : IDL.Func([IDL.Principal], [IDL.Vec(WishlistItem)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeWishlistItem' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'productUrl' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'minAge' : IDL.Nat,
    'platform' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Text,
    'occasion' : IDL.Text,
    'gender' : IDL.Text,
    'category' : IDL.Text,
    'maxAge' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const WishlistItem = IDL.Record({
    'productUrl' : IDL.Text,
    'name' : IDL.Text,
    'productId' : IDL.Nat,
    'platform' : IDL.Text,
    'imageUrl' : IDL.Text,
    'forMember' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'stylePreferences' : IDL.Vec(IDL.Text),
  });
  const ProductFilter = IDL.Record({
    'color' : IDL.Opt(IDL.Text),
    'maxPrice' : IDL.Opt(IDL.Float64),
    'occasion' : IDL.Opt(IDL.Text),
    'gender' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
    'minPrice' : IDL.Opt(IDL.Float64),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [IDL.Nat], []),
    'addWishlistItem' : IDL.Func([WishlistItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
    'getUserProducts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWishlist' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(WishlistItem)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeWishlistItem' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };